// This file is auto-generated by `supabase gen types typescript`
// Run: pnpm --filter supabase gen:types
//
// Do not edit manually. Re-generate after any migration change.

export type Database = {
  public: {
    Tables: {
      events: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          venue_name: string | null;
          venue_id: string | null;
          city: string;
          category: string;
          tags: string[];
          price: string | null;
          price_cents_min: number | null;
          start_time: string;
          end_time: string | null;
          date: string;
          location: unknown; // PostGIS geography
          image_url: string | null;
          source: string;
          source_id: string | null;
          source_url: string | null;
          status: string;
          submitted_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["events"]["Row"], "id" | "date" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["events"]["Insert"]>;
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          role: string;
          home_city: string | null;
          push_token: string | null;
          created_at: string;
          updated_at: string;
        };
      };
      saved_events: {
        Row: {
          id: string;
          user_id: string;
          event_id: string;
          created_at: string;
        };
      };
      community_submissions: {
        Row: {
          id: string;
          submitted_by: string;
          title: string;
          description: string | null;
          venue_name: string | null;
          city: string | null;
          category: string | null;
          tags: string[];
          price: string | null;
          start_time: string | null;
          end_time: string | null;
          lat: number | null;
          lng: number | null;
          image_url: string | null;
          status: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          rejection_reason: string | null;
          created_at: string;
        };
      };
      event_sources: {
        Row: {
          id: string;
          name: string;
          base_url: string | null;
          scraper_file: string | null;
          last_scraped_at: string | null;
          is_active: boolean;
          event_count: number;
          created_at: string;
        };
      };
      venues: {
        Row: {
          id: string;
          name: string;
          address: string | null;
          city: string | null;
          location: unknown;
          website: string | null;
          created_at: string;
        };
      };
    };
    Functions: {
      nearby_events: {
        Args: {
          user_lat: number;
          user_lng: number;
          radius_miles?: number;
          category_filter?: string | null;
          time_filter?: string;
        };
        Returns: {
          id: string;
          title: string;
          description: string | null;
          venue_name: string | null;
          city: string;
          category: string;
          tags: string[];
          price: string | null;
          start_time: string;
          end_time: string | null;
          image_url: string | null;
          source: string;
          source_url: string | null;
          lat: number;
          lng: number;
          distance_miles: number;
          is_happening_now: boolean;
        }[];
      };
    };
  };
};
